apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
  namespace: team1
spec:
  chart:
    git: https://github.com/nniikkoollaaii/GitOps_K8s_Cluster_via_Terraform_Config_Team1
    path: "helm/example"
    secretRef: 
      name: "git-auth"
    releaseName: app1
    version: 1.0.0
    targetNamespace: team1